[package]
name = "dexrouter_extended"
version = "1.1.5"
published-at = "0xfb62ac68863a8cf5066a04171ea173c49051049a460163304bd4a938f0a7ef3a"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.48.2" }
scallop = { local = "../interfaces/scallop" }
scallop_treasury = { local = "../interfaces/scallop/scallop_treasury" }
X = { local = "../interfaces/scallop/x" }
scallop_math = { local = "../interfaces/scallop/scallop_math" }
scallop_coin_decimals_registry = { local = "../interfaces/scallop/scallop_coin_decimals_registry" }
scallop_whitelist = { local = "../interfaces/scallop/scallop_whitelist" }
scallop_oracle = { local = "../interfaces/scallop/scallop_oracle" }
AlphaFi = { local = "../interfaces/alphafi" }
SuiSystem = { git = "https://github.com/MystenLabs/sui.git", rev = "mainnet-v1.48.2", subdir = "crates/sui-framework/packages/sui-system" }
haedal = { local = "../interfaces/haedal" }
mmt_v3 = { local = "../interfaces/momentum/mmt_v3" }
slippage_check = { local = "../interfaces/momentum/slippage_check" }
BluefinSpot = { local = "../interfaces/bluefin" }
MetaVault = { local = "../interfaces/meta-vault" }
magma = { local = "../interfaces/magma" }
steamm = { local = "../interfaces/steamm" }

[addresses]
dexrouter_extended = "0x0"
sui = "0000000000000000000000000000000000000000000000000000000000000002"
sui_system = "0000000000000000000000000000000000000000000000000000000000000003"
magma = "0x4a35d3dfef55ed3631b7158544c6322a23bc434fe4fca1234cb680ce0505f82d"