[package]
name = "wormhole"
published-at = "0x5306f64e312b581766351c07af79c72fcb1cd25147157fdc2f8ad76de9a3fb6a"
# https://github.com/wormhole-foundation/wormhole/blob/main/sui/wormhole/Move.toml

[addresses]
wormhole = "0x5306f64e312b581766351c07af79c72fcb1cd25147157fdc2f8ad76de9a3fb6a"
