[package]
name = "magma"
version = "0.0.1"
#edition = "2024.beta"
published-at = "0x183af2adf115f331105825ae63e1d7d3c848d67beb4d60bc36208a90a5e92f4b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.48.2" }
magma_utils = { local = "../magma_utils" }
magma_math = { local = "../magma_math" }
magma_gauge = { local = "../magma_gauge" }

[addresses]
magma_utils = "0x682eaba7450909645bf949db3fc5881432a00b49b4c06d6974ecc4ee684e7992"
magma_math = "0x659c0e9c4c8a416f040fa758d4fc4073a5fdd1fed97edadcd5cba5180fb36246"
magma_gauge = "0x2de81c0f5cc2aa176da9f093834efbf846d581afa46516bf4952b6efd3a44992"
magma = "0x4a35d3dfef55ed3631b7158544c6322a23bc434fe4fca1234cb680ce0505f82d"
